'use strict';

// PASSO 15 — CEO/Orchestrator V1 (SHADOW MODE). Enums centrais. Princípio central em todo este
// módulo: CEO_INTELLIGENCE != EXECUTION_AUTHORITY — nada aqui executa nada real.

// item 1 — loop de decisão do CEO.
const CEO_LOOP_STAGES = [
  'OBSERVE', 'DIAGNOSE', 'PRIORITIZE', 'GENERATE_CONSUME_ALTERNATIVES', 'CHALLENGE', 'RANK',
  'RECOMMEND', 'POLICY_EVALUATION', 'SHADOW_EXECUTION', 'OBSERVE_OUTCOME_WHEN_AVAILABLE', 'LEARN', 'REPLAN',
];

// item 1 — orientação principal única por ciclo. Em SHADOW_MODE, EXECUTE nunca é execução real —
// vira WOULD_EXECUTE_IF_AUTHORIZED (ver shadowMode.js).
const CEO_ORIENTATIONS = ['EXECUTE', 'DO_NOT_EXECUTE', 'COLLECT_EVIDENCE', 'HOLD_CAPITAL', 'KILL_HYPOTHESIS', 'SWITCH_PRODUCT'];

// item 3 — hierarquia de fonte de verdade, do mais forte pro mais fraco. HYPOTHESIS nunca é
// promovida silenciosamente a evidência.
const SOURCE_OF_TRUTH_LEVELS = ['FINANCIAL_TRANSACTION_TRUTH', 'PLATFORM_TRUTH', 'BEHAVIORAL_TRUTH', 'STRATEGIC_INFERENCE', 'HYPOTHESIS'];

// item 4 — restrição dominante (extensível — nunca hardcoda a resposta atual).
const DOMINANT_CONSTRAINT_CATEGORIES = [
  'MEASUREMENT', 'ACQUISITION', 'CONVERSION', 'OFFER', 'ECONOMICS', 'PRODUCT_VIABILITY',
  'INSUFFICIENT_EVIDENCE', 'EXECUTION', 'CAPITAL', 'RETENTION_LIFECYCLE', 'UNKNOWN',
];

// item 5 — classificação de um problema identificado. Nem toda métrica ruim é bottleneck.
const PROBLEM_CLASSIFICATIONS = ['BOTTLENECK', 'OPPORTUNITY', 'DEPENDENCY', 'SYMPTOM'];

// item 6 — router de relevância.
const RELEVANCE_TIERS = ['CRITICAL_NOW', 'RELEVANT', 'BACKGROUND', 'NOT_RELEVANT_THIS_CYCLE'];

// item 8 — relações entre candidatos.
const CANDIDATE_RELATIONS = ['CONFLICTS_WITH', 'DEPENDS_ON', 'ENABLES', 'COMPLEMENTS', 'SUPERSEDES', 'INDEPENDENT'];

// item 11 — só permitido quando alternativas são REALMENTE incomparáveis.
const NO_DEFENSIBLE_PREFERENCE = 'NO_DEFENSIBLE_PREFERENCE';

// item 13 — desafio de status quo, nunca privilegiando o produto atual por padrão.
const STATUS_QUO_CHALLENGE_CONCLUSIONS = [
  'KEEP_CURRENT_PRODUCT', 'CHANGE_OFFER', 'CHANGE_FUNNEL', 'CHANGE_PRICE', 'ADD_BACKEND',
  'CHANGE_CHANNEL', 'PAUSE_ACQUISITION', 'SWITCH_PRODUCT', 'BUILD_NEW_PRODUCT', 'HOLD_CAPITAL',
];

// item 14 — hierarquia de objetivo econômico, do mais fundamental pro mais avançado.
const ECONOMIC_OBJECTIVE_HIERARCHY = [
  'PROTECT_FINANCIAL_TRUTH', 'PROTECT_CAPITAL', 'RESTORE_ACHIEVE_ECONOMIC_VIABILITY',
  'GENERATE_RELIABLE_LEARNING', 'REACH_REPEATABLE_PROFITABILITY', 'SCALE_PROFITABLE_SYSTEMS',
  'INCREASE_AOV_LTV_BACKEND_REVENUE', 'ALLOCATE_CAPITAL_TO_HIGHEST_MARGINAL_OPPORTUNITY',
  'DIVERSIFY_WHEN_ECONOMICALLY_JUSTIFIED', 'MAXIMIZE_SUSTAINABLE_ABSOLUTE_PROFIT',
];

// item 16 — escalada de viabilidade de produto.
const PRODUCT_VIABILITY_ESCALATION_STATES = ['CONTINUE_VALIDATION', 'PAUSE_PRODUCT', 'KILL_PRODUCT', 'SWITCH_PRODUCT'];

// item 22 — framework de qualidade de decisão.
const DECISION_QUALITY_STATES = [
  'GOOD_DECISION_GOOD_OUTCOME', 'GOOD_DECISION_BAD_OUTCOME', 'BAD_DECISION_GOOD_OUTCOME',
  'BAD_DECISION_BAD_OUTCOME', 'INSUFFICIENT_EVIDENCE_TO_JUDGE',
];

// item 26 — modos de falha, nunca virando decisão inventada.
const FAILURE_MODES = [
  'STALE_DATA', 'MISSING_FINANCIAL_TRUTH', 'CONFLICTING_AGENTS', 'NO_ACTIONABLE_CANDIDATE',
  'MEASUREMENT_BLOCKED', 'POLICY_BLOCKED', 'AUTHORITY_BLOCKED', 'CIRCUIT_BREAKER_OPEN',
  'INSUFFICIENT_EVIDENCE', 'DEPENDENCY_BLOCKED',
];

module.exports = {
  CEO_LOOP_STAGES, CEO_ORIENTATIONS, SOURCE_OF_TRUTH_LEVELS, DOMINANT_CONSTRAINT_CATEGORIES,
  PROBLEM_CLASSIFICATIONS, RELEVANCE_TIERS, CANDIDATE_RELATIONS, NO_DEFENSIBLE_PREFERENCE,
  STATUS_QUO_CHALLENGE_CONCLUSIONS, ECONOMIC_OBJECTIVE_HIERARCHY, PRODUCT_VIABILITY_ESCALATION_STATES,
  DECISION_QUALITY_STATES, FAILURE_MODES,
};
